// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
    // compile proto definitions
    tonic_build::compile_protos("proto/user.proto").expect("Failed to compile protos");
}
